name: esp32 port

env:
  # GitHub tag of ESP-IDF to use for CI (note: must be a tag or a branch)
  IDF_VER: v5.0.2

on:
  push:
  pull_request:
    paths:
      - '.github/workflows/*.yml'
      - 'tools/**'
      - 'py/**'
      - 'extmod/**'
      - 'shared/**'
      - 'lib/**'
      - 'drivers/**'
      - 'ports/esp32/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_idf50:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4

    - name: Cached ESP-IDF install
      id: cache-esp-idf
      uses: actions/cache@v3
      with:
        path: |
          ./esp-idf/
          ~/.espressif/
          !~/.espressif/dist/
          ~/.cache/pip/
        key: esp-idf-${{ env.IDF_VER }}

    - name: Install ESP-IDF packages
      if: steps.cache-esp-idf.outputs.cache-hit != 'true'
      run: source tools/ci.sh && ci_esp32_idf50_setup

    - name: Build
      run: source tools/ci.sh && ci_esp32_build
